const ENDPOINTS = {
  REGISTER: "/register",
  AGENTREGISTER: "/agentregister",
  LOGIN: "/login",
  USERS: "/users",
  LIVEUSER: "/liveusers",
  GOLIVE: "/go-live",
  HOME: "/users",
  USERDETAIL: "/user",
  LIVESTATUS: "/get_live_status",
  ADDTIP: "/add-tip",
  TIP: "/tip",
  SUBMITTOKEN: "submit-token",
  UPDATETOKEN: "updatetoken",
  CREATE_RAZORPAY_ORDER: "create-order",
  VERIFY_PAYMENT: "/verify-payment",
  TIPHISTORY: "/token",
  SETPRIVATESHOW: "/set-private-show",
  PRIVATESHOWREQUEST: "/privateshowrequest",
  PRIVATEREQUEST: "/private-requests",
  STARTPRIVATESHOW: "/start-private-show",
  ENDSHOW:"/complete-private-show",

  CREATORESHOWREQUEST: "/creator-private-requests",
  ADMINREQUEST: "/admin-private-requests",
  

  ALLUSER: "/alluser",
  DELETEUSER: "/deleteuser",
  UPDATEUSERSTATUS: "/updateuserstatus",
  TIPTRANSECTION: "/tiptransection",
  RECHARGEHISTORY: "/rechargehistory",
  WITHDRAWALHISTORY: "/withdrawal-history",
  WITHDRAWALREQUEST: "/withdrawal",
  ADMINWITHDRAWALREQUEST: "/admin-withdrawal-history",
  UPDATEWITHDRAWAL: "/update-withdrawal",
  ADMINDASHBOARD: "/admindashboard",
  SAVESETTING: "/settings/save",
  GETSETTING: "/settings/get",

  AGENTUSER: "/agentuser",
  AGENTLIVEUSER: "/agentliveuser",
};

export default ENDPOINTS;
